# Site settings
title: Bucket List Coder
header-img: img/home-bg.jpg
email: chantellebecker1@gmail.com
copyright_name: Chantelle Becker/Bucket List Coder
description: "The Bucket List Coder - The technical (and life) lessons learned along the journey to becoming a better devleoper."
baseurl: ""
url: "http://yourdomain.com"
instagram_username: ohheychantay
twitter_username: ohheychantay
github_username:  chantellebecker 
facebook_username:  chantelle.welp
email_username:  chantellebecker1@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
